# This is a basic workflow to help you get started with Actions

name: Code Test

on:
  pull_request:
    branches: [ master ]

jobs:
  test-success:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
